spring.application.name=UberApp

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=tejaDb@890
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

#server.error.include-message=always
#server.error.include-binding-errors=always

#smtp config
spring.mail.username=tejakoribilli8892@gmail.com
spring.mail.password=gjut vcip kiic rfoo
spring.mail.port=587
spring.mail.host=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#security config
jwt.secretKey = nmgfsnglkbnlk5jdsfehrfgesfbgh654dvjhdafjbk5jsdbljshnbljhnguyhhiu092j
